classname: pipelines.wind_cube_profile_sta.pipeline.WindCubeProfile

triggers:
  # - .*\.sta.7z  # Remove or make more specific to local file pattern
  - .*sb.lidar.z01.*\.sta.7z

retriever:
  path: pipelines/wind_cube_profile_sta/config/retriever.yaml

dataset:
  path: pipelines/wind_cube_profile_sta/config/dataset.yaml
  overrides:
    /attrs/location_id: sb
    /attrs/location_meaning: "Site B"
    /data_vars/longitude/data: -97.558676
    /data_vars/latitude/data: 36.231763

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
