# https://github.com/tsdat/tsdat/blob/main/examples/templates/ingest_pipeline_template.yml
# or open an existing example in this repository to see what you can do here. Note that
# the A2e program uses slightly different metadata conventions than tsdat and a
# reviewer can help you determine which metadata should be included here.

pipeline:
  type: Ingest

  # These parameters will be used to name files.
  location_id: "rufus"
  dataset_name: "met_z03"
  # qualifier: ""
  # temporal: ""
  data_level: "b0" # If not applying QC this should be set to "a0"

dataset_definition:
  attributes:
    title: "met_z03"
    description: "Example data ingest for the A2e AWAKEN project. Data doi: 10.21947/1328928"
    conventions: MHKiT-Cloud Data Standards v. 1.0
    institution: Atmosphere to Electrons
    code_url: https://github.com/a2edap/ingest-awaken
    location_meaning: "Rufus, OR"

  dimensions:
    time:
      length: unlimited

  variables:
    time:
      input:
        name: datetime
        # converter:
        #   classname: tsdat.utils.converters.StringTimeConverter
        #   parameters:
        #     timezone: UTC
        #     time_format: "%Y/%m/%d %H:%M:%S"
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    wind_speed_mean: # Name of variable in the output file
      input:
        name: "S" # Name of variable in the input file
        # units: m        # Units the input variable was measured in. Provide this if
        # the output units are different and you want tsdat to do the
        # conversion.
      dims:
        [time] # List of coordinates that dimension this variable. `time` is
        # a very common dimension, sometimes `height`, too.
      type: float # The data type, typically one of: `float`, `long`, `int`
      attrs:
        long_name: Wind Speed # Label used by Xarray and other libraries for plotting
        standard_name: "wind_speed" # Standard name from the CF Standard names table.
        # Provide this if possible, otherwise remove it.
        comment: "Mean horizontal wind speed" # User-friendly description of the property.
        height_AGL_m: 3
        units:
          m/s # Units attribute from the CF Standard list of units.
          # Always provide this, even for 'unitless' quantities –
          # set `units: "1"` for such quantities.

    wind_speed:
      input:
        name: "U"
      dims: [time]
      type: float
      attrs:
        long_name: Wind Speed
        comment: "Resultant mean wind speed"
        height_AGL_m: 3
        units: m/s

    wind_dir:
      input:
        name: "U_dir"
      dims: [time]
      type: float
      attrs:
        long_name: Wind Direction
        standard_name: "wind_from_direction"
        comment: "Resultant mean wind direction"
        height_AGL_m: 3
        units: deg

    wind_direction_std:
      input:
        name: "U_dir_std"
      dims: [time]
      type: float
      attrs:
        long_name: Wind Direction Std Dev
        comment: "Standard deviation of wind direction"
        height_AGL_m: 3
        units: deg

    temperature:
      input:
        name: "T"
      dims: [time]
      type: float
      attrs:
        long_name: Air Temperature
        standard_name: "air_temperature"
        comment: "Standard deviation of wind direction"
        height_AGL_m: 2
        units: deg_C

    rel_humidity:
      input:
        name: "RH"
      dims: [time]
      type: float
      attrs:
        long_name: Relative Humidity
        standard_name: "relative_humidity"
        comment: ""
        height_AGL_m: 2
        units: "%"

    pressure:
      input:
        name: "P"
      dims: [time]
      type: float
      attrs:
        long_name: Air Pressure
        standard_name: "air_pressure"
        comment: "Barometric pressure (not corrected for sea-level)"
        height_AGL_m: 2
        units: "mb"

    E_downwelling_shortwave:
      input:
        name: "E"
      dims: [time]
      type: float
      attrs:
        long_name: Shortwave Radiation
        standard_name: "downwelling_shortwave_radiance_in_air"
        comment: "downwelling shortwave solar radiation (wavelength = 400-1100 nm)"
        height_AGL_m: 2
        units: "W/m^2"

    T_datalogger:
      input:
        name: "T_10X"
      dims: [time]
      type: float
      attrs:
        comment: "10X datalogger temperature"
        height_AGL_m: 2
        units: "deg_C"

    V_datalogger:
      input:
        name: "P_10X"
      dims: [time]
      type: float
      attrs:
        comment: "10X datalogger power"
        height_AGL_m: 2
        units: "V"

    latitude:
      data: 45.6911
      type: float
      attrs:
        long_name: "North latitude"
        standard_name: "latitude"
        comment: "Recorded lattitude at the instrument location"
        units: "degree_N"
        valid_range: [-90.f, 90.f]

    longitude:
      data: -120.7457
      type: float
      attrs:
        long_name: "East longitude"
        standard_name: "longitude"
        comment: "Recorded longitude at the instrument location"
        units: "degree_E"
        valid_range: [-180.f, 180.f]

    altitude:
      data: 63
      type: float
      attrs:
        long_name: "Altitude"
        standard_name: "altitude"
        comment: "Recorded altitude at the instrument location"
        units: m

#-----------------------------------------------------------------
quality_management:
  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - time

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.SortDatasetByCoordinate
        parameters:
          ascending: True
          correction: "Coordinate data was sorted in order to ensure monotonicity."
    variables:
      - time

  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS
    exclude: [latitude, longitude, altitude]

  # TODO – Developer: Update this as needed.
  # manage_custom_qc: # Rename this
  #   checker:
  #     classname: ingest.met_z03.pipeline.qc.CustomQualityChecker
  #   handlers:
  #     - classname: ingest.met_z03.pipeline.qc.CustomQualityHandler
