pipeline:
  type: Ingest

  # These parameters will be used to name files.
  location_id: "awaken"
  dataset_name: "aml_ld_z01"
  # qualifier: ""
  # temporal: ""
  data_level: "a0" # If not applying QC this should be set to "a0"

dataset_definition:
  attributes:
    title: "aml_ld_z01"
    description: "awaken lidar disdrometer ingest"
    conventions: MHKiT-Cloud Data Standards v. 1.0
    institution: Atmosphere to Electrons
    code_url: https://github.com/a2edap/ingest-awaken
    location_meaning: "awaken"

  dimensions:
    time:
      length: unlimited

  variables:
    time:
      input:
        name: time
        converter:
          classname: tsdat.utils.converters.StringTimeConverter
          parameters:
            timezone: UTC
            time_format: "%d.%m.%Y %H:%M:%S"
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    precip_intensity:
      input:
        name: "Intensity of precipitation (mm/h)"
      dims: [time]
      type: float
      attrs:
        long_name: Precipitation Intensity
        comment: ""
        units: mm/h

    precip_total:
      input:
        name: "Precipitation since start (mm)"
      dims: [time]
      type: float
      attrs:
        long_name: Total Precipitation
        comment: "Precipitation since start of recording"
        units: mm

    weather_code_synop:
      input:
        name: "Weather code SYNOP WaWa"
      dims: [time]
      type: str
      attrs:
        comment: "Weather code SYNOP WaWa"

    weather_code_metar:
      input:
        name: "Weather code METAR/SPECI"
      dims: [time]
      type: str
      attrs:
        comment: "Weather code METAR SPECI"

    weather_code_nws:
      input:
        name: "Weather code NWS"
      dims: [time]
      type: str
      attrs:
        comment: "Weather code NWS"

    radar_reflectivity:
      input:
        name: "Radar reflectivity (dBz)"
      dims: [time]
      type: float
      attrs:
        comment: "Radar reflectivity"
        units: dBz

    visibility:
      input:
        name: "MOR Visibility (m)"
      dims: [time]
      type: float
      attrs:
        comment: "MOR Visibility"
        units: m

    amplitude:
      input:
        name: "Signal amplitude of Laserband"
      dims: [time]
      type: float
      attrs:
        comment: "Signal amplitude of Laserband"
        units: dB

    n_particles:
      input:
        name: "Number of detected particles"
      dims: [time]
      type: float
      attrs:
        comment: "Number of detected particles"
        units: count

    sensor_temperature:
      input:
        name: "Temperature in sensor (Â°C)"
      dims: [time]
      type: float
      attrs:
        comment: "Temperature in sensor body"
        units: deg C

    heating_current:
      input:
        name: "Heating current (A)"
      dims: [time]
      type: float
      attrs:
        comment: "heating current sent to sensor body"
        units: A

    sensor_voltage:
      input:
        name: "Sensor voltage (V)"
      dims: [time]
      type: float
      attrs:
        comment: "Sensor voltage"
        units: V

    optics_status:
      input:
        name: "Optics status"
      dims: [time]
      type: str
      attrs:
        comment: "Optics status"

    kinetic_energy:
      input:
        name: "Kinetic Energy"
      dims: [time]
      type: float
      attrs:
        comment: "Kinetic energy of precipitation"
        units: J

    snow_intensity:
      input:
        name: "Snow intensity (mm/h)"
      dims: [time]
      type: float
      attrs:
        comment: "snow intensity"
        units: mm/h

    latitude: # TODO
      data: 71.323
      type: float
      attrs:
        long_name: "North latitude"
        standard_name: "latitude"
        comment: "Recorded lattitude at the instrument location"
        units: "degree_N"
        valid_range: [-90.f, 90.f]

    longitude: # TODO
      data: -156.609
      type: float
      attrs:
        long_name: "East longitude"
        standard_name: "longitude"
        comment: "Recorded longitude at the instrument location"
        units: "degree_E"
        valid_range: [-180.f, 180.f]

    altitude: # TODO
      data: 4000.0
      type: float
      attrs:
        long_name: "Altitude"
        standard_name: "altitude"
        comment: "Recorded altitude at the instrument location"
        units: m

#-----------------------------------------------------------------
quality_management:
  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - time

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.SortDatasetByCoordinate
        parameters:
          ascending: True
          correction: "Coordinate data was sorted in order to ensure monotonicity."
    variables:
      - time

  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS
    exclude:
      [
        weather_code_synop,
        weather_code_metar,
        weather_code_nws,
        optics_status,
        latitude,
        longitude,
        altitude,
      ]
