# https://github.com/tsdat/tsdat/blob/main/examples/templates/ingest_pipeline_template.yml
# or open an existing example in this repository to see what you can do here. Note that
# the A2e program uses slightly different metadata conventions than tsdat and a
# reviewer can help you determine which metadata should be included here.

pipeline:
  type: Ingest

  # These parameters will be used to name files.
  location_id: "richland"
  dataset_name: "ecor_richland"
  # qualifier: ""
  temporal: "30min"
  data_level: "b0" # If not applying QC this should be set to "a0"

dataset_definition:
  attributes:
    title: "ecor"
    description: "eddy correlation flux measurement system (https://www.arm.gov/publications/tech_reports/handbooks/ecor_handbook.pdf)"
    conventions: MHKiT-Cloud Data Standards v. 1.0
    institution: Atmosphere to Electrons
    code_url: https://github.com/a2edap/ingest-awaken
    location_meaning: "richland"

  dimensions:
    time:
      length: 0
    var:
      length: 7
    var*:
      length: 7

  variables:
    time:
      input:
        name: time
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
    var:
      input:
        name: var
      dims: [var]
      type: str
      attrs:
        description: "u_wind, v_wind, w_wind, temperature, water vapor density, carbon dioxide density, wind magnitude"
    var*:
      input:
        name: var*
      dims: [var*]
      type: str
      attrs:
        description: "u_wind, v_wind, w_wind, temperature, water vapor density, carbon dioxide density, wind magnitude"

    u_mean:
      input:
        name: u_average
      dims: []
      type: float
      attrs:
        comment: "average air velocity u direction"
        units: m/s
    v_mean:
      input:
        name: v_average
      dims: []
      type: float
      attrs:
        comment: "average air velocity v direction"
        units: m/s
    w_mean:
      input:
        name: w_average
      dims: []
      type: float
      attrs:
        comment: "average air velocity w direction"
        units: m/s
    T_mean:
      input:
        name: T_average
      dims: []
      type: float
      attrs:
        comment: "average air temperature"
        units: K
        valid_range: [207, 407]
    q_mean:
      input:
        name: q_average
      dims: []
      type: float
      attrs:
        comment: "average water vapor density"
        units: kg/m^3
        valid_range: [0, 2000]
    c_mean:
      input:
        name: c_average
      dims: []
      type: float
      attrs:
        comment: "average carbon dioxide density"
        units: kg/m^3
        valid_range: [8, 32]
    V_mean:
      input:
        name: V_average
      dims: []
      type: float
      attrs:
        comment: "average windspeed"
        units: m/s

    u_mean_spk:
      input:
        name: u_spike
      dims: []
      type: float
      attrs:
        comment: "average air velocity u direction 'spike'"
        units: m/s
    v_mean_spk:
      input:
        name: v_spike
      dims: []
      type: float
      attrs:
        comment: "average air velocity v direction 'spike'"
        units: m/s
    w_mean_spk:
      input:
        name: w_spike
      dims: []
      type: float
      attrs:
        comment: "average air velocity w direction 'spike'"
        units: m/s
    T_mean_spk:
      input:
        name: T_spike
      dims: []
      type: float
      attrs:
        comment: "average air temperature 'spike'"
        units: K
    q_mean_spk:
      input:
        name: q_spike
      dims: []
      type: float
      attrs:
        comment: "average water vapor density 'spike'"
        units: kg/m^3
    c_mean_spk:
      input:
        name: c_spike
      dims: []
      type: float
      attrs:
        comment: "average carbon dioxide density 'spike'"
        units: kg/m^3
    V_mean_spk:
      input:
        name: V_spike
      dims: []
      type: float
      attrs:
        comment: "average windspeed 'spike'"
        units: m/s

    u_var:
      input:
        name: u_variance
      dims: []
      type: float
      attrs:
        comment: "air velocity u direction variance"
        units: m/s
    v_var:
      input:
        name: v_variance
      dims: []
      type: float
      attrs:
        comment: "air velocity v direction variance"
        units: m/s
    w_var:
      input:
        name: w_variance
      dims: []
      type: float
      attrs:
        comment: "air velocity w direction variance"
        units: m/s
    T_var:
      input:
        name: T_variance
      dims: []
      type: float
      attrs:
        comment: "air temperature variance"
        units: K
    q_var:
      input:
        name: q_variance
      dims: []
      type: float
      attrs:
        comment: "water vapor density variance"
        units: kg/m^3
    c_var:
      input:
        name: c_variance
      dims: []
      type: float
      attrs:
        comment: "carbon dioxide density variance"
        units: kg/m^3
    V_var:
      input:
        name: V_variance
      dims: []
      type: float
      attrs:
        comment: "windspeed variance"
        units: m/s

    u_skew:
      input:
        name: u_skewness
      dims: []
      type: float
      attrs:
        comment: "air velocity u direction skewness"
        units: m/s
    v_skew:
      input:
        name: v_skewness
      dims: []
      type: float
      attrs:
        comment: "air velocity v direction skewness"
        units: m/s
    w_skew:
      input:
        name: w_skewness
      dims: []
      type: float
      attrs:
        comment: "air velocity w direction skewness"
        units: m/s
    T_skew:
      input:
        name: T_skewness
      dims: []
      type: float
      attrs:
        comment: "air temperature skewness"
        units: K
    q_skew:
      input:
        name: q_skewness
      dims: []
      type: float
      attrs:
        comment: "water vapor density skewness"
        units: kg/m^3
    c_skew:
      input:
        name: c_skewness
      dims: []
      type: float
      attrs:
        comment: "carbon dioxide density skewness"
        units: kg/m^3
    V_skew:
      input:
        name: V_skewness
      dims: []
      type: float
      attrs:
        comment: "windspeed skewness"
        units: m/s

    u_kurt:
      input:
        name: u_kurtosis
      dims: []
      type: float
      attrs:
        comment: "air velocity u direction kurtosis"
        units: m/s
    v_kurt:
      input:
        name: v_kurtosis
      dims: []
      type: float
      attrs:
        comment: "air velocity v direction kurtosis"
        units: m/s
    w_kurt:
      input:
        name: w_kurtosis
      dims: []
      type: float
      attrs:
        comment: "air velocity w direction kurtosis"
        units: m/s
    T_kurt:
      input:
        name: T_kurtosis
      dims: []
      type: float
      attrs:
        comment: "air temperature kurtosis"
        units: K
    q_kurt:
      input:
        name: q_kurtosis
      dims: []
      type: float
      attrs:
        comment: "water vapor density kurtosis"
        units: kg/m^3
    c_kurt:
      input:
        name: c_kurtosis
      dims: []
      type: float
      attrs:
        comment: "carbon dioxide density kurtosis"
        units: kg/m^3
    V_kurt:
      input:
        name: V_kurtosis
      dims: []
      type: float
      attrs:
        comment: "windspeed kurtosis"
        units: m/s

    u_mean_rot:
      input:
        name: u_rotated
      dims: []
      type: float
      attrs:
        comment: "average 'rotated' air velocity u direction"
        units: m/s
    v_mean_rot:
      input:
        name: v_rotated
      dims: []
      type: float
      attrs:
        comment: "average 'rotated' air velocity v direction"
        units: m/s
    w_mean_rot:
      input:
        name: w_rotated
      dims: []
      type: float
      attrs:
        comment: "average 'rotated' air velocity w direction"
        units: m/s
    T_mean_rot:
      input:
        name: T_rotated
      dims: []
      type: float
      attrs:
        comment: "average 'rotated' air temperature"
        units: deg C
    q_mean_rot:
      input:
        name: q_rotated
      dims: []
      type: float
      attrs:
        comment: "average 'rotated' water vapor density"
        units: kg/m^3
    c_mean_rot:
      input:
        name: c_rotated
      dims: []
      type: float
      attrs:
        comment: "average 'rotated' carbon dioxide density"
        units: kg/m^3
    V_mean_rot:
      input:
        name: V_rotated
      dims: []
      type: float
      attrs:
        comment: "average 'rotated' windspeed"
        units: m/s

    covariance:
      input:
        name: covariance
      dims: [var, var*]
      type: float
      attrs:
        comment: "variable covariance matrix"

    covariance_rot:
      input:
        name: covariance_rotated
      dims: [var, var*]
      type: float
      attrs:
        comment: "'rotated' variable covariance matrix"

    sensible_heat_flux:
      input:
        name: sensible_heat_flux
      dims: []
      type: float
      attrs:
        comment: "sensible heat flux (H)"
        units: W/m^2
    latent_heat_flux:
      input:
        name: latent_heat_flux
      dims: []
      type: float
      attrs:
        comment: "latent heat flux (Lv_E)"
        units: W/m^2
    momentum_flux:
      input:
        name: momentum_flux
      dims: []
      type: float
      attrs:
        comment: "momentum flux (dynamic) (M)"
        units: kg/(m s^2)
    shear_velocity:
      input:
        name: friction_velocity
      dims: []
      type: float
      attrs:
        comment: "shear or friction velocity (u_*)"
        units: m/s
    c_flux:
      input:
        name: CO2_flux
      dims: []
      type: float
      attrs:
        comment: "carbon dioxide flux (F_{CO2})"
        units: umol/(m^2 s)

    wind_speed:
      input:
        name: wind_speed
      dims: []
      type: float
      attrs:
        comment: "average wind speed (horizontal)"
        units: m/s
    wind_direction:
      input:
        name: wind_direction
      dims: []
      type: float
      attrs:
        comment: "average wind direction (horizontal)"
        units: deg from N
    wind_angle_vertical:
      input:
        name: wind_rotation_vertical
      dims: []
      type: float
      attrs:
        comment: "wind mean vertical angle (from horizontal plane)"
        units: deg
    wind_angle_horizontal:
      input:
        name: wind_rotation_horizontal
      dims: []
      type: float
      attrs:
        comment: "wind mean horizontal angle"
        units: deg
    wind_direction_std:
      input:
        name: wind_direction_std
      dims: []
      type: float
      attrs:
        comment: "average wind direction (horizontal) standard deviation"
        units: deg
    wind_angle_vertical_std:
      input:
        name: wind_vertical_std
      dims: []
      type: float
      attrs:
        comment: "standard devation of wind vertical angle (from horizontal plane)"
        units: deg

    specific_heat:
      input:
        name: specific_heat
      dims: []
      type: float
      attrs:
        comment: "specific heat capacity of air"
        units: J/(kg K)
    specific_heat_50RH:
      input:
        name: specific_heat_50%RH
      dims: []
      type: float
      attrs:
        comment: "specific heat capacity of air at 50% relative humidity"
        units: J/(kg K)
    heat_of_vaporization:
      input:
        name: heat_of_vaporization
      dims: []
      type: float
      attrs:
        comment: "heat of vaporization of air"
        units: J/(kg K)
    heat_of_vaporization_50RH:
      input:
        name: heat_of_vaporization_50%RH
      dims: []
      type: float
      attrs:
        comment: "heat of vaporization of air at 50% relative humidity"
        units: J/mol
    air_density:
      input:
        name: moist_air_density
      dims: []
      type: float
      attrs:
        comment: "moist air density"
        units: kg/m^3
    air_density_50RH:
      input:
        name: moist_air_density_50%RH
      dims: []
      type: float
      attrs:
        comment: "moist air density at 50% relative humidity"
        units: kg/m^3
    mixing_ratio:
      input:
        name: mixing_ratio
      dims: []
      type: float
      attrs:
        comment: "mass ratio of water in air (specific humidity)"
        units: kg/kg
    mixing_ratio_50RH:
      input:
        name: mixing_ratio_50%RH
      dims: []
      type: float
      attrs:
        comment: "mass ratio of water in air (specific humidity) at 50% relative humidity"
        units: kg/kg

    q_irga_signal_strength:
      input:
        name: irga_H20
      dims: []
      type: float
      attrs:
        comment: "average signal strength of water vapor optical signal"
    c_irga_signal_strength:
      input:
        name: irga_C02
      dims: []
      type: float
      attrs:
        comment: "average signal strength of carbon dioxide optical signal"
    irga_pressure:
      input:
        name: irga_pressure
      dims: []
      type: float
      attrs:
        comment: "air pressure within irga electronics enclosure"
        units: kPa
    irga_temp:
      input:
        name: irga_temperature
      dims: []
      type: float
      attrs:
        comment: "air temperature within irga electronics enclosure"
        units: deg C
    irga_cooler_voltage:
      input:
        name: irga_cooler
      dims: []
      type: float
      attrs:
        comment: "mean irga cooling system voltage"
        units: V
    irga_status:
      input:
        name: irga_status
      dims: []
      type: float
      attrs:
        comment: "irga status code"

#-----------------------------------------------------------------
quality_management:
  #---------------------------------------------------------------
  # manage_missing_coordinates:
  #   checker:
  #     classname: tsdat.qc.checkers.CheckMissing
  #   handlers:
  #     - classname: tsdat.qc.handlers.FailPipeline
  #   variables:
  #     - time

  # manage_coordinate_monotonicity:
  #   checker:
  #     classname: tsdat.qc.checkers.CheckMonotonic
  #   handlers:
  #     - classname: tsdat.qc.handlers.SortDatasetByCoordinate
  #       parameters:
  #         ascending: True
  #         correction: "Coordinate data was sorted in order to ensure monotonicity."
  #   variables:
  #     - time

  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS

  manage_min_values:
    checker:
      classname: tsdat.qc.checkers.CheckValidMin
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 2
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS

  manage_max_values:
    checker:
      classname: tsdat.qc.checkers.CheckValidMax
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 4
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS

  # TODO â€“ Developer: Update this as needed.
  # manage_custom_qc: # Rename this
  #   checker:
  #     classname: ingest.ecor_richland.pipeline.qc.CustomQualityChecker
  #   handlers:
  #     - classname: ingest.ecor_richland.pipeline.qc.CustomQualityHandler
