attrs:
  title: Lowspeed Flux
  dataset_name: flux_lowspeed_21544
  description: AWAKEN Low speed data from surface flux station
  institution: Atmosphere to Electrons
  location_id: nwtc
  location_meaning: NREL Flatirons Test Site
  data_level: a1
  # qualifier: wind
  # temporal: 1s
  conventions: MHKiT-Cloud Data Standards v1.0

coords:
  time:
    attrs:
      long_name: Time (UTC)
      units: Seconds since 1970-01-01 00:00:00
    dims:
      - time
    dtype: datetime64[s]
data_vars:
  air_temperature:
    attrs:
      description:
        Air temperature is the bulk temperature of the air, not the surface (skin)
        temperature.
      long_name: Air Temperature
      units: degC
    dims:
      - time
    dtype: float
  relative_humidity:
    attrs:
      description:
        The ratio of the vapor pressure to the saturation vapor pressure with respect to
        water.
      long_name: Relative Humidity
      units: "%"
    dims:
      - time
    dtype: float
  surface_air_pressure:
    attrs:
      description:
        Air pressure is the force per unit area which would be exerted when the moving
        gas molecules of which the air is composed strike a theoretical surface of any
        orientation.
      long_name: Surface Air Pressure
      units: hPa
    dims:
      - time
    dtype: float
  wind_speed:
    attrs:
      description:
        Speed is the magnitude of velocity. Wind is defined as a two-dimensional
        (horizontal) air velocity vector, with no vertical component. (Vertical motion
        in the atmosphere has the standard name upward_air_velocity.)
      long_name: Wind Speed
      units: m/s
    dims:
      - time
    dtype: float

  latitude:
    data: 39.909692
    dims: []
    dtype: float
    attrs:
      long_name: "North latitude"
      standard_name: "latitude"
      comment: "Recorded lattitude at the instrument location"
      units: "degN"
  longitude:
    data: -105.228052
    dims: []
    dtype: float
    attrs:
      long_name: "East longitude"
      standard_name: "longitude"
      comment: "Recorded longitude at the instrument location"
      units: "degE"
  altitude:
    data: 1828
    dims: []
    dtype: float
    attrs:
      long_name: "Altitude"
      standard_name: "altitude"
      comment: "Recorded altitude at the instrument location"
      units: m
