# https://github.com/tsdat/tsdat/blob/main/examples/templates/ingest_pipeline_template.yml
# or open an existing example in this repository to see what you can do here. Note that
# the A2e program uses slightly different metadata conventions than tsdat and a
# reviewer can help you determine which metadata should be included here.

pipeline:
  type: Ingest

  # These parameters will be used to name files.
  location_id: "nwtc"
  dataset_name: "assist_nwtc"
  # qualifier: ""
  # temporal: ""
  data_level: "b0" # If not applying QC this should be set to "a0"

dataset_definition:
  attributes:
    title: "assist"
    description: "Ingest for summary ASSIST data"
    conventions: MHKiT-Cloud Data Standards v. 1.0
    institution: Atmosphere to Electrons
    code_url: https://github.com/a2edap/ingest-awaken
    location_meaning: "nwtc"

  dimensions:
    time:
      length: unlimited
    wnum:
      length: unlimited

  variables:
    time:
      input:
        name: time
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    ABBapexTemp:
      attrs:
        long_name:
          Temperature of the ambient black body measured at apex, top, and bottom
          (in overall summary file)
        units: degree Celsius
      dims: [time]
      input:
        name: ABBapexTemp
      type: float
    ABBtopTemp:
      attrs:
        long_name:
          Temperature of the ambient black body measured at apex, top, and bottom
          (in overall summary file)
        units: degree Celsius
      dims: [time]
      input:
        name: ABBtopTemp
      type: float
    ABBbottomTemp:
      attrs:
        long_name:
          Temperature of the ambient black body measured at apex, top, and bottom
          (in overall summary file)
        units: degree Celsius
      dims: [time]
      input:
        name: ABBbottomTemp
      type: float
    HBBapexTemp:
      attrs:
        long_name:
          Temperature of the hot black body measured at apex, top, and bottom
          (in overall summary file)
        units: degrees Celsius
      dims: [time]
      input:
        name: HBBapexTemp
      type: float
    HBBbottomTemp:
      attrs:
        long_name:
          Temperature of the hot black body measured at apex, top, and bottom
          (in overall summary file)
        units: degrees Celsius
      dims: [time]
      input:
        name: HBBbottomTemp
      type: float
    HBBtopTemp:
      attrs:
        long_name:
          Temperature of the hot black body measured at apex, top, and bottom
          (in overall summary file)
        units: degrees Celsius
      dims: [time]
      input:
        name: HBBtopTemp
      type: float
    LWresponsivity:
      attrs:
        long_name:
          Average responsivity of the long-wave detector (in overall summary
          file)
        units: Unknown
      dims: [time]
      input:
        name: LWresponsivity
      type: float
    SWresponsivity:
      attrs:
        long_name:
          Average responsivity of the short-wave detector (in overall summary
          file)
        units: Unknown
      dims: [time]
      input:
        name: SWresponsivity
      type: float
    # base_time:
    #   attrs:
    #     long_name: Days since 01 Jan 1970
    #     units: Days
    #   input:
    #     name: base_time
    #   type: float
    detectorStirlingCoolerBlockTemp:
      attrs:
        long_name:
          Temperature of the cooling block, related to cooling power  (in overall
          summary file)
        units: degrees Celsius
      dims: [time]
      input:
        name: detectorStirlingCoolerBlockTemp
      type: float
    frontEndEnclosureTemp:
      attrs:
        long_name: Temperature of the front end of the enclosure (in overall summary file)
        units: degrees Celsius
      dims: [time]
      input:
        name: frontEndEnclosureTemp
      type: float
    hatchOpen:
      attrs:
        long_name: "Status of the hatch:

          1=open

          0=closed

          -1=undetermined

          (in overall summary file)"
        units: Unitless
      dims: [time]
      input:
        name: hatchOpen
      type: float
    interferometerHumidity:
      attrs:
        long_name: Relative humidity at the interferometer (in overall summary file)
        units: "%"
      dims: [time]
      input:
        name: interferometerHumidity
      type: float
    interferometerTemp:
      attrs:
        long_name: Temperature of the interferometer (in overall summary file)
        units: degrees Celsius
      dims: [time]
      input:
        name: interferometerTemp
      type: float
    mean_Tb_675_680:
      attrs:
        long_name:
          Mean brightness temperature in the range of wavelengths indicated in
          the header in cm-1 (in overall summary file)
        units: K
      dims: [time]
      input:
        name: mean_Tb_675_680
      type: float
    mean_Tb_985_990:
      attrs:
        long_name:
          Mean brightness temperature in the range of wavelengths indicated in
          the header in cm-1 (in overall summary file)
        units: K
      dims: [time]
      input:
        name: mean_Tb_985_990
      type: float
    mean_imaginary_rad_985_990:
      attrs:
        long_name:
          Imaginary part of the radiance in the range of wavelengths indicated
          in the header in cm-1 (in overall summary file)
        units: mW/(m2 sr cm-1)
      dims: [time]
      input:
        name: mean_imaginary_rad_985_990
      type: float
    mean_rad:
      attrs:
        long_name: Spectral radiance (in channel A, B files)
        units: mW/(m2 sr cm-1)
      dims: [time]
      input:
        name: mean_rad
      type: float

    latitude:
      data: 71.323
      type: float
      attrs:
        long_name: "North latitude"
        standard_name: "latitude"
        comment: "Recorded lattitude at the instrument location"
        units: "degree_N"
        valid_range: [-90.f, 90.f]

    longitude:
      data: -156.609
      type: float
      attrs:
        long_name: "East longitude"
        standard_name: "longitude"
        comment: "Recorded longitude at the instrument location"
        units: "degree_E"
        valid_range: [-180.f, 180.f]

    altitude:
      data: 4000.0
      type: float
      attrs:
        long_name: "Altitude"
        standard_name: "altitude"
        comment: "Recorded altitude at the instrument location"
        units: m

#-----------------------------------------------------------------
quality_management:
  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - COORDS

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.SortDatasetByCoordinate
        parameters:
          ascending: True
          correction: "Coordinate data was sorted in order to ensure monotonicity."
    variables:
      - COORDS

  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS
    exclude: [latitude, longitude, altitude]

  # # TODO â€“ Developer: Update this as needed.
  # manage_custom_qc: # Rename this
  #   checker:
  #     classname: ingest.assist_nwtc.pipeline.qc.CustomQualityChecker
  #   handlers:
  #     - classname: ingest.assist_nwtc.pipeline.qc.CustomQualityHandler
