storage:
  # This section should not be modified unless there is a strong need. Please contact
  # the repository maintainers if you feel you need to use different settings here â€“
  # there may be another way to accomplish what you need.
  classname: ${STORAGE_CLASSNAME}
  parameters:
    retain_input_files: ${RETAIN_INPUT_FILES}
    root_dir: /srv/data/nfs/assist/Assist-11/processed
    bucket_name: ${STORAGE_BUCKET}

  file_handlers:
    input:
      my_custom_format: # Solely used as a label. See the 'csv' input
        file_pattern: .*assistsummary.*.cdf
        classname: ingest.assist_nwtc.pipeline.filehandler.CustomFileHandler

    # The output section should not be modified unless there is a strong need. Please
    # contact the repository maintainers if you feel you need to write to a different
    # format.
    output:
      netcdf:
        file_extension: ".nc"
        classname: tsdat.io.filehandlers.NetCdfHandler
