pipeline:
  type: Ingest

  # These parameters will be used to name files.
  location_id: "nwtc"
  dataset_name: "wind_cube_nacelle_rtd"
  # qualifier: ""
  # temporal: ""
  data_level: "b0" # If not applying QC this should be set to "a0"

dataset_definition:
  attributes:
    title: "wind_cube_nacelle"
    description: "Wind cube v2 ingest"
    conventions: MHKiT-Cloud Data Standards v. 1.0
    institution: Atmosphere to Electrons
    code_url: https://github.com/a2edap/ingest-awaken
    location_meaning: "nwtc"

  dimensions:
    time:
      length: unlimited

  variables:
    time:
      input:
        name: Timestamp
        converter:
          classname: tsdat.utils.converters.StringTimeConverter
          parameters:
            timezone: UTC
            time_format: "%Y-%m-%dT%H:%M:%S"
      dims: [time]
      type: long
      attrs:
        long_name: Time (UTC)
        standard_name: time
        units: seconds since 1970-01-01T00:00:00

    CNR:
      attrs:
        long_name: Carrier-to-noise ratio along the line of sight (real-time data).
        units: dB
      dims: [time]
      input:
        name: CNR
      type: float

    DRWS:
      attrs:
        long_name: Radial wind speed standard deviation (real-time data)
        units: m/s
      dims: [time]
      input:
        name: DRWS
      type: float

    Distance:
      attrs:
        long_name: Measurement plan distance (real-time data).
        units: m
      dims: [time]
      input:
        name: Distance
      type: float

    LOS_index:
      attrs:
        long_name: Current line of sight (real-time data).
        units: NA
      dims: [time]
      input:
        name: LOS_index
      type: float

    Overrun_Status:
      attrs:
        long_name: Real-time performance status (real-time data).
        units: NA
      dims: [time]
      input:
        name: Overrun_Status
      type: float

    RWS:
      attrs:
        long_name: Radial wind speed along the current line of sight (real-time data).
        units: m/s
      dims: [time]
      input:
        name: RWS
      type: float

    RWS_Status:
      attrs:
        long_name: Radial wind speed status (real-time data).
        units: NA
      dims: [time]
      input:
        name: RWS_Status
      type: float

    Roll:
      attrs:
        long_name: Roll angle of the system (real-time data).
        units: deg
      dims: [time]
      input:
        name: Roll
      type: float

    Tilt:
      attrs:
        long_name: Tilt angle of the system (real-time data).
        units: deg
      dims: [time]
      input:
        name: Tilt
      type: float

    latitude:
      data: 71.323
      type: float
      attrs:
        long_name: "North latitude"
        standard_name: "latitude"
        comment: "Recorded lattitude at the instrument location"
        units: "degree_N"
        valid_range: [-90.f, 90.f]

    longitude:
      data: -156.609
      type: float
      attrs:
        long_name: "East longitude"
        standard_name: "longitude"
        comment: "Recorded longitude at the instrument location"
        units: "degree_E"
        valid_range: [-180.f, 180.f]

    altitude:
      data: 4000.0
      type: float
      attrs:
        long_name: "altitude"
        standard_name: "altitude"
        comment: "Recorded altitude at the instrument location"
        units: m

#-----------------------------------------------------------------
quality_management:
  #---------------------------------------------------------------
  manage_missing_coordinates:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.FailPipeline
    variables:
      - COORDS

  manage_coordinate_monotonicity:
    checker:
      classname: tsdat.qc.checkers.CheckMonotonic
    handlers:
      - classname: tsdat.qc.handlers.SortDatasetByCoordinate
        parameters:
          ascending: True
          correction: "Coordinate data was sorted in order to ensure monotonicity."
    variables:
      - COORDS

  #---------------------------------------------------------------
  manage_missing_values:
    checker:
      classname: tsdat.qc.checkers.CheckMissing
    handlers:
      - classname: tsdat.qc.handlers.RemoveFailedValues
      - classname: tsdat.qc.handlers.RecordQualityResults
        parameters:
          bit: 1
          assessment: Bad
          meaning: "Value is equal to _FillValue or NaN"
    variables:
      - DATA_VARS
    exclude: [latitude, longitude, altitude]

  # # TODO â€“ Developer: Update this as needed.
  # manage_custom_qc: # Rename this
  #   checker:
  #     classname: ingest.wind_cube_profile.pipeline.qc.CustomQualityChecker
  #   handlers:
  #     - classname: ingest.wind_cube_profile.pipeline.qc.CustomQualityHandler
